gamestore/urls.py
from django.urls import path
from gamestore import views
from gamestore.views import CatalogView, MyGamesView
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    login, logout
)

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^login/$', login, {'template_name':'login.html'}, name='login'),
    #url(r'^catalog/', TemplateView.as_view(template_name="catalog.html"),
    #               name='catalog'),
    url(r'^catalog/', CatalogView.as_view(), name='catalog'),
    url(r'^gameregistration/$', views.gameregistration, name='gameregistration'),
    url(r'^game/$', views.game, name='game'),
    url(r'^mygames/', MyGamesView.as_view(), name='mygames'),
    url(r'^playgame/$', views.playgame, name='playgame'),
    url(r'^purchase/$', views.purchase, name='purchase'),
    #url(r'^catalog/$', views.get_games, name='get_games'),
]

gamestore/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class StoreUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #name = models.CharField(max_length = 150, unique = True, null=True)
    #user_email = models.EmailField(blank = True, null=True)
    #user_password = models.CharField(max_length = 30, null=True)
    developer = models.IntegerField(default=0)
    money = models.PositiveIntegerField(default=100)

    #class Meta:
        #managed = True


    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        StoreUser.objects.create(user=instance)
    instance.storeuser.save()

    """def set_as_developer(self):
        self.developer = True;
        self.save()

    def get_is_developer(self):
        return self.developer"""

"""@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        StoreUser.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.storeuser.save()"""

#Luo profiilin
"""def create_profile(sender, **kwargs):
    #Jos käyttäjäobjekti on luotu, niin profiili luodaan.
    if kwargs['created']:
        user_profile = StoreUser.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)"""

class Game(models.Model):
    game_name = models.CharField(max_length = 150, blank = True, null=True)
    game_url = models.URLField(null=True)
    game_info = models.TextField(blank = True, null = True)
    high_score = models.IntegerField(default = 0, null=True)
    player = models.ForeignKey("StoreUser", on_delete = models.CASCADE, null = True, related_name = "game" )

class AllGames(models.Model):
    game_name = models.CharField(max_length = 150, blank = True, null=True)
    game_url = models.URLField(null=True)
    info = models.TextField(blank=True)
    high_score = models.IntegerField(default = 0, null=True)
    developer_id = models.ForeignKey("StoreUser", on_delete = models.CASCADE, null = True, related_name = "game_in_store")
    sold = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.game_name

    #def add_new_game(self):
    #def remove_game(self):

class Sales(models.Model):
    date = models.DateField(auto_now_add=True)
    sold_game = models.ForeignKey("AllGames", on_delete = models.CASCADE, null = True, related_name = "sales_info")

class Store(models.Model):
    id = models.AutoField(primary_key=True)
    pid = models.PositiveIntegerField(default =0, blank = False, null = False)
    sid = models.CharField(max_length = 20, blank = False, null = False, default="xdxachepeedzsnhs")
    key = models.CharField(max_length = 50, blank = False, null = False, default="22bb869888dc66715cf61785277bfad3")
    amount = models.PositiveIntegerField(default =0, blank = False, null = False)
    checksum = models.CharField(max_length = 100, blank = False, null = False, default="")

gamestore/templates/catalog.html
<!DOCTYPE HTML>
<html>
<head>
  <title>Pelikaupan testi</title>
  <meta charset="utf-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script language="javascript" src=http://code.createjs.com/createjs-2015.11.26.min.js></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  {% load static %}
  <!--<script src="{% static 'gamestore/catalog/catalog.js' %}"></script>
  <img id=arrow_right src="{% static 'gamestore/images/arrow_right.png' %}" hidden=True></img>
  <img id=arrow_left src="{% static 'gamestore/images/arrow_left.png' %}" hidden=True></img>-->
  <link rel="stylesheet" type="text/css" href="{% static 'gamestore/store.css' %}" />
</head>
<body>
  <center>
  <canvas id="game_catalog_canvas"></canvas>
  <div>
    <h1 id="Gamestore_title"> Game store </h1>
  </div>
  {% for game in allgames %}
    <div>
      <form action="{% url 'game' %}" method="post">
        {% csrf_token %}
        <input type="number" name="game_id" value="{{game.id}}" hidden=True>
        <button type="submit" class="btn" id="{{game.id}}">{{game.game_name}}</button>
      </form>
    </div>
    <br>
  {% endfor %}
  </center>
</body>
</html>

gamestore/templates/frontpage.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cool gamestore for cool games</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'gamestore/store.css' %}" />

  </head>

  <body>
    <script>
      function hideIntro() {
        document.getElementById("intro").style.display = "none";

      }
    </script>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">This is a gamestore where you can browse and buy games or register as a developer to add your own game to the store</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Options</h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="text-white"> Log out </a></li>
                <li><a href="{% url 'mygames' %}" class="text-white"> My games </a></li>
                  {% for storeuser in storeusers %}
                    {% if storeuser.user.id == user.id and storeuser.developer == 1 %}

                      <li><a href="{% url 'gameregistration' %}" class="text-white"> Register a game </a></li>

                    {% endif %}
                  {% endfor %}
                {% else %}
                <li><a href="{% url 'login' %}" class="text-white"> Log in </a></li>
                <li><a href="{% url 'register' %}" class="text-white"> Register </a></li>
                {% endif %}
                {% if user.developer == 1 %}
                <li><a href="{% url 'gameregistration' %}" class="text-white"> Register a game </a></li>
                <li><a href="{% url 'logout' %}" class="text-white"> Log out </a></li>
                {% endif %}

              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <!--<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>-->
            <img src="{% static 'gamestore/images/icon.png' %}" alt="store icon" height="30" width="30">
            <strong>Cool gamestore</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center" id="intro">
        <div class="container">
          <h1 class="jumbotron-heading">Cool gamestore</h1>
          <p class="lead text-muted">Here you can browse awesome games to suit your needs. There are dozens of them. DOZENS!</p>
          <p>
            <!--<a href="#" class="btn btn-primary my-2">Browse popular games</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>-->
            <button type="button" class="btn btn-primary" onclick="hideIntro()">Browse cool games</button>
          </p>
        </div>
      </section>
      <iframe id="catalog" height=700 width="100%" src="{% url 'catalog' %}">
      </iframe>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>TIE-23500</p>
        <p>Hie no harkka tyä</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>

gamestore/templates/game.html
<!DOCTYPE HTML>
<html>
<head>
  <title>Pelikaupan testi</title>
  <meta charset="utf-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'gamestore/store.css' %}" />
</head>
<body>
  <center>
    <div>
      <h1> {{game.game_name}} </h1>
    </div>
    <div>
      <h5> {{game.info}} </h5>
    </div>
    <div>
      <h5> Price: {{game.price}} </h5>
      <h5> {{user.id}} </h5>
    </div>

    <form action="{% url 'purchase' %}" method="post">
      {% csrf_token %}
      <input type="number" name="game_id" value="{{game.id}}" hidden=True>
      <input type="number" name="game_price" value="{{game.price}}" hidden=True>
      <button type="submit" class="btn">Buy</button>
    </form>
  </center>
</body>
</html>

gamestore/templates/gameregistration.html
<!DOCTYPE HTML>
<html>
<head>
  <title> Register a game </title>
  <meta charset="utf-8" />
  <link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
  crossorigin="anonymous">

</head>
</body>
  <br>
  <div class="container" id="register">
    <h1> Welcome </h1>
    <form method="post" id="registerform">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Submit">
    </form>
  </div>
</body>
</html>

gamestore/templates/login.html
<!DOCTYPE HTML>
<html>
<head>
  <title> Log In </title>
  <meta charset="utf-8" />
  <link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
  crossorigin="anonymous">
</head>
</body>
<br>
  <div class="container" id="login">
    <h1> Game Store </h1>
    <form method="post" id="loginform">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Submit"><br>
      Not registered?
      <a href="{% url 'register' %}"> Click here </a>
  </div>
</body>
</html>

gamestore/templates/logout.html
<!DOCTYPE html>
<html>
  <head>
    <title> Log out </title>
    <meta charset="utf-8" />
    <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1 class="display-1">
        <small class="text-muted">Logged Out</small>
      </h1>
    </div>
  </body>
</html>

gamestore/templates/mygames.html
<!DOCTYPE HTML>
<html>
<head>
  <title> Register a game </title>
  <meta charset="utf-8" />
  <link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
  crossorigin="anonymous">

</head>
</body>
<center>
  <br>
  {% for game in mygames %}
  <div>
      <form action="{% url 'playgame' %}" method="post">
        {% csrf_token %}
        <input type="number" name="game_id" value="{{game.id}}" hidden=True>
        <button type="submit" class="btn" id="{{game.id}}">{{game.game_name}}</button>

      </form>
  </div>
  <br>
  {% endfor %}
<center>
</body>
</html>

gamestore/templates/playgame.html
<!DOCTYPE HTML>
<html>
<head>
  <title>Pelikaupan testi</title>
  <meta charset="utf-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'gamestore/store.css' %}" />
</head>
<body>
  <center>
    <div>
      <h1> {{game.game_name}} </h1>
    </div>
    <div>
      <h5> {{game.info}} </h5>
    </div>
    <iframe WIDTH=1000 HEIGHT=1000 src="{{game.game_url}}"></iframe>
  </center>
</body>
</html>

gamestore/templates/purchase.html
<!DOCTYPE HTML>
<html>
<head>
  <title>Pelikaupan testi</title>
  <meta charset="utf-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'gamestore/store.css' %}" />
</head>
<body>
  <center>
    <form action="https://simplepayments.herokuapp.com/pay/" method="POST">
    <input type="hidden" name="pid" value={{gamepurchase.pid}} />
    <input type="hidden" name="sid" value={{gamepurchase.sid}} />
    <input type="hidden" name="success_url"
            value="https://young-river-70675.herokuapp.com/" />
    <input type="hidden" name="cancel_url"
            value="https://young-river-70675.herokuapp.com/" />
    <input type="hidden" name="error_url"
            value="https://young-river-70675.herokuapp.com/" />
    <input type="hidden" name="checksum"
            value={{gamepurchase.checksum}} />

    <label for="id_amount">Amount</label>
    <input type="text" id="id_amount" name={{gamepurchase.amount}} value="5" />
    <input type="submit" value="Accept Payment"/>
</form>
  </center>
</body>
</html>

gamestore/templates/register.html
<!DOCTYPE HTML>
<html>
<head>
  <title> Register </title>
  <meta charset="utf-8" />
  <link rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
  integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
  crossorigin="anonymous">

</head>
</body>
  <br>
  <div class="container" id="register">
    <h1> Welcome </h1>
    <form method="post" id="registerform">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-default" type="submit" value="Submit">
    </form>
  </div>
</body>
</html>